apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::822805556133:role/renren-app-logging-rw-role
  name: renren-app-logging-rw
  namespace: renren-stg