---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: renren-fast-vue-internet
spec:
  gateways:
  - istio-system/internet-gw
  hosts:
  - renren.dev.demo.cn
  http:
  - match:
    - port: 80
      uri:
        prefix: /portal
    - port: 443
      uri:
        prefix: /portal 
    rewrite:
       uri: " "
    retries: {}
    route:
    - destination:
        host: renren-fast-vue
        port:
          number: 80
        subset: stable
      weight: 100