apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renren-stg

images:
- name: 984601295324.dkr.ecr.eu-central-1.amazonaws.com/renren/renren-fast-vue
  newName: 984601295324.dkr.ecr.eu-central-1.amazonaws.com/renren/renren-fast-vue
  newTag: stg-fc55f5dc-45

# - hpa.yaml
resources:
- ../../base
- hpa.yaml
- serviceaccount.yaml
- logging.yaml
- service-monitor.yaml
- istio-dr.yaml
- istio-svc.yaml
- istio-internetfacing.yaml

commonLabels:
  env: stg

patches:
- path: dep-version-patch.yaml
  target:
    kind: Deployment

patchesStrategicMerge:
- patch-deployment.yaml

configMapGenerator:
- behavior: merge
  envs:
  - app-configmap.txt
  name: renren-fast-vue-configmap
- behavior: merge
  files:
  - application.yaml
  name: renren-fast-vue-configuration

secretGenerator:
- behavior: merge
  envs:
  - app-secrets.txt
  name: renren-fast-vue-secrets
  type: Opaque
- behavior: create
  files:
  - application-secret-files.yaml
  name: renren-fast-vue-secret-files
  options:
    disableNameSuffixHash: true
  type: Opaque
