---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::822805556133:role/renren-renren-fast-vue-sa
  name: renren-fast-vue-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: renren-fast-vue-role
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
    - pods
    - services
    - configmaps
  verbs:
    - get
    - list
    - watch
